- README.md
FYI: Finally got my port to STM32L432 to run the `serial` example. Cross-referencing https://github.com/dmitrystu/libusb_stm32 was quite helpful. Not sure at all about the naming, as L432, L442, L433, L443 all seem to be the same (apart from LCD/AES additions).
> Reference to STM32L432 driver implementation

- Cargo.toml
- src/test_class.rs
We're using usb-device with our peripheral in high speed mode, and needed to increase the buffer sizes in the test class.  
In high speed mode, the max size for bulk packets is 512 bytes, and 1024 for interrupt packets.
Thanks for your work on this awesome Rust USB stack!
> Support high speed operation for test class with feature

- src/control_pipe.rs
- src/device.rs
This PR fixes an issue with the processing order of multiple EP0 events.
Specifically, if both EP0-IN and EP0-OUT events have occurred, we **have** to process EP0-IN first so that we update the `ControlState` properly. Otherwise, we inadvertently process the EP0-OUT status phase as a spurious OUT transfer (instead of the STATUS phase as expected).
This only occurs when both EP0-OUT and EP0-IN transactions occur at the same time, which occurs when polling is completed at a lower-than-continuous rate.
After this fix, this crate can be used in `debug` configuration reliably as well.
> Fixing processing order of EP0 (control) transactions

- src/descriptor.rs
- src/device.rs
- src/device_builder.rs
This PR adds minimal support for composite devices with IADs (interface association descriptors). The motivation is to enable out-of-the-box support of composite devices containing CDC-ACM serial ports and other USB functions (such as HID devices) on Windows.
Some references:
https://www.usb.org/sites/default/files/iadclasscode_r10.pdf
https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-interface-association-descriptor
https://www.microchip.com/forums/m189607.aspx
https://community.arm.com/developer/tools-software/tools/f/keil-forum/29075/win7-cdc-hid-only-com-port-works
> Add basic IAD support

- src/test_class.rs
The imxrt-usbd driver requires that the user sets the EP0 max packet
size to 64 bytes. To meet the requirement in our test_class example,
we need access to the UsbDeviceBuilder. Ideally, we could access the
builder without duplicating the make_device method.
This commit adds a new method, make_device_builder, for the test
class. It sets the required device properties, then returns the
builder to the caller for any additional configurations.
> Add make_device_builder to test class

- README.md
We're working on a usb-device implementation for NXP's i.MX RT
microcontrollers. As of this writing, the driver passes the usb-device
test suite, and it plays well with usbd-serial. Though the peripheral
supports high speed, we're limiting the driver to full speed, since
the usb-device ecosystem doesn't seem high-speed capable.
Not sure if you're still advertising hardware driver crates. But I
figured I'd add a new item, and take the chance to say thanks for
putting this usb-device ecosystem together.
> Add imxrt-usbd to the hardware driver crates list

- Cargo.toml
- tests/test_class_host/device.rs
- tests/test_class_host/main.rs
- tests/test_class_host/tests.rs
It appears that the original libusb is no longer maintained. In anticipation of adding isochronous endpoints to the test class (someday, anyway), this PR upgrades to rusb, which appears to be the most commonly used libusb fork.
The only change was replacing the lifetime parameter of `DeviceHandle`s with a `UsbContext`, which I hardcoded to the `Context` struct.
I tested this by deploying test_class firmware to a imxrt1062 and running the test, all ten cases passed:
```
test_class_host starting
looking for device...
running 10 tests
test control_request ... ok
test control_data ... ok
test control_data_static ... ok
test control_error ... ok
test string_descriptors ... ok
test interface_descriptor ... ok
test bulk_loopback ... ok
test interrupt_loopback ... ok
test bench_bulk_write ... ok …
```
> Switch from libusb to rusb

- src/descriptor.rs
Adds a method for writing descriptors with an unknown length in a way that's similar to how accepting control transfers works, and a method for writing endpoint descriptors with extra data in the same manner.
Unfortunately the naming is the reverse of control transfers (`write_with` takes a callback while `accept_with` takes a buffer), but this way it's compatible.
This would implement both #63 and #46. @Windfisch, if you have an audio driver going, could you test this to see if it's good for your purposes?
> Add methods to make descriptor writing more flexible

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/bus.rs
- src/control.rs
- src/control_pipe.rs
- src/device.rs
- src/endpoint.rs
- src/lib.rs
- Hidden behind defmt-impl feature
(similar to how heapless handles defmt)
> Defmt support for enums and structs

- CHANGELOG.md
- src/device.rs
- Per (https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-11100-32-bit%20Cortex-M4-Microcontroller-SAM4S_Datasheet.pdf; 40.6.3 page 1042), the state transition from Suspend should go back to the previous state
- Previously Suspend would always transition back to Default state
- Fixes #96
> Fix Suspend state transition to go back to the previous state (#96)

- src/lib.rs
- field xxx is never read
- associated funct xxx is never used
- Used _ to ignore the used fields and function
> Fix compiler warnings

- tests/test_class_host/device.rs
- tests/test_class_host/tests.rs
The `bulk_loopback` device test sends a zero-length packet (ZLP) from host to device when the bulk endpoint packet size is a multiple of the max packet size (MPS). Before this commit, the MPS was hard-coded to 64, the MPS of the full-speed bulk endpoint. This commit updates the test to use the MPS that matches the full- / high-speed test class's MPS.
I was having issues testing a high-speed device with the test suite before this change (compiling both firmware and test suite with `test-class-high-speed` feature). Specifically, the test would fail when trying to read back data from the 65 byte transfer. I think I traced the issue back to this condition, but let me know if you think there might be an issue in my device driver. There's more notes in the commit message.
> Device tests: Send bulk packet ZLP based on max packet size

- README.md
The old link returned 404 as the file driver.rs was removed. Point to the crate root directory instead.
Alternatively, the link could point to the docs at https://docs.embassy.dev/embassy-usb/git/default/index.html
> Fix link to embassy-usb

- CHANGELOG.md
- src/bus.rs
- src/descriptor.rs
- src/endpoint.rs
- src/lib.rs
- src/test_class.rs
- tests/test_class_host/tests.rs
Aim is to resolve https://github.com/mvirkkunen/usb-device/issues/33, however as @lkolbly points out it doesn't add testing support.  @mvirkkunen is that OK with you, or should I look in to adding test support?  I expect any practical use of isochronous endpoints to not use the current endpoint buffering arrangement (the `copy_to_nonoverlapping()` takes a fair bit of processor time), so a test that transfers data in/out of an isochronous endpoint would currently be a bit artificial.
This will also need a minor version bump, assuming we're following semver.
@sibiryakov - any comments?
> Add enumerations and allocator for isochronous endpoints

- src/descriptor.rs
- src/device.rs
- src/device_builder.rs
- src/lib.rs
In some usecases it is desirable to select a lower revision of the USB standard (eg when a KVM between the device and the host does not handle usb 2.1 very well).
This allows a device to use a different usb revision (choices limited by an enum).
> Add the ability to select USB revision

- README.md
Some of the links to class crates were outdated (404s). This PR makes them point to the repositories currently specified on crates.io.
(Side note: this is the second time I'm submitting this PR, I think something went wrong on my end. Sorry if this is a duplicate!)
> Fix 404s in README

- .github/workflows/ci.yml
- .github/workflows/rustfmt.yml
Requires:
- https://github.com/rust-embedded-community/usb-device/pull/123
> Update actions dependencies

- CHANGELOG.md
- src/lib.rs
`UsbError` is as primitive as it gets, and there are situations where the error has to be duplicated (for example to put it in an error event in a non-blocking queue).
Unless there are grand plans for the `UsbError` enum that will add references to data in the future, it would help me to add `Clone`. The other ones are mostly suggestions based on best practices.
> Add copy and eq to UsbError

- CHANGELOG.md
- src/control_pipe.rs
Fixes #128 by updating the library to ignore `ep_in_status` on the EP0 control pipe when in the `Idle` state.
If the device gets a zero-length-packet while transmitting the last portion of an EP0-IN transmission, it will internally transition to the `Idle` state immediately and essentially "forget" that it just sent an EP0-IN packet, so it was erroring when getting an indication that this packet successfully transmitted.
> Fixing an issue with windows device enumeration

- CHANGELOG.md
- Cargo.toml
- src/descriptor.rs
- src/descriptor/lang_id.rs
- src/device.rs
- src/device_builder.rs
- src/lib.rs
- src/test_class.rs
This PR builds on #122 by unifying strings under a single `StringDescriptors` structure to keep things organized a little differently. This eases usage on the end-user, as previously the borrowed slices had to be `&'static` borrows, which complicated the construction when i.e. a serial number was read from EEPROM or some other source.
> Refactoring language management for simplicity

- CHANGELOG.md
- Cargo.toml
This PR prepares for a release of usb-device 0.3.0 - I've tested these updates on Stabilizer with a patched dependency chain and I've got PRs ready for a few different crates to update the API.
cc @ithinuel, @jordens
> Release `usb-device` 0.3.0

- CHANGELOG.md
- src/lib.rs
It seems like most uses of usb-device now require the LangID enum, so this PR adds it to the preludes.
> Provide `LangID` via preludes

- CHANGELOG.md
- Cargo.toml
- README.md
- src/device_builder.rs
- src/lib.rs
If https://github.com/rust-embedded-community/usb-device/pull/133 is accepted, this should have the explicit `use` for `LangID` removed from the example code.
> Documentation updates

- src/class.rs
- src/device.rs
- src/test_class.rs
I've been playing around with the [Microsoft OS String Descriptors](https://github.com/pbatard/libwdi/wiki/WCID-Devices#microsoft-os-string-descriptor) (specifically to get the winusb driver installed on my device) and everything was working fine on 0.2.9 but the update to 0.3.0 (#122) introduced a behavior difference. 
The change in #122 requires that  `req.index` be a valid lang id, if not, it exits early and doesn't call the `get_string` method. 
I also thought lang id could be set to a default in order to not get a breaking change but I think it obscures that LangId might not be set for all requests? 
Any thoughts appreciated. I'm just dabbling on embedded stuff so I could be missing something.
> Make LangID optional on get_string()

- CHANGELOG.md
- Cargo.toml
- src/control_pipe.rs
- src/device.rs
- src/lib.rs
- src/macros.rs
This PR does a few things:
1. Adds in a new logging feature to make it easy to trace USB debug issues in the future (I've written this a few times, and figured it would be useful as a general feature instead)
2. Removed the `set_error()` calls when processing a SETUP packet. We are not allowed to error in this state and should simply ignore the SETUP packet instead.
3. Changed the handling of EP0-IN-complete tokens. We were being pretty jumpy with getting these tokens in unexpected states, however this is simply an indication that a packet transmission completed. We may have updated state internally and lost track of what we sent. As such, I've updated it such that we just ignore these tokens if we don't need them in our current state instead of stalling the control pipe, as this isn't …
> Adding USB tracing, fixing further enumeration issues

- src/control_pipe.rs
- src/device.rs
- src/macros.rs
Fixes #113 by handling all the various `Result<>` types and propogating them upwards to `poll()`. For now, they are simply logged. In the future, it could be helpful to push these outwards and have `poll()` return the `Result<>` type, however I'm hesitant to introduce a breaking API change right now. I'll spawn an issue for this.
This also fixes #58 by propagating the errors described to the new log macros.
> Handling `Result`s throughout the crate

- CHANGELOG.md
- Cargo.toml
This PR prepares the crate for a 0.3.2 release to get some fixes out. Specifically, this should reduce code size for users and fix issues with Windows enumeration.
I'm going to look at some API updates for a 0.4 release later and want to cut these changes out as a patch before we go down a semver-breaking update again, since there's a lot of downstream dependencies to update as well.
> Preparing for 0.3.2 release

- README.md
As suggested on Matrix, this PR adds usbd-midi to the list of class crates in the readme file.
> Add usbd-midi to class crates list in readme

- CHANGELOG.md
- src/bus.rs
* UsbBus is Sync --> the resulting UsbDevice is Sync.
* UsbBus is not Sync --> compiler error due to unsatisfied trait bound
* UsbBus is Sync --> the resulting UsbDevice is Sync.
* UsbBus is not Sync --> the resulting UsbDevice is *not* Sync
In other words, it is _safe_ to allow a non-Sync UsbBus because Rust will NOT derive Sync for the UsbDevice in this case.
I have a hard-real-time firmware application which uses the USB interface to provide secondary (non-real-time) diagnostics. I poll the UsbDevice in my main loop, while all my other real-time stuff is handled in various interrupts. I do not use USB interrupts and I never access the UsbDevice from an interrupt context.
Unfortunately, making the UsbBus Sync requires the use of critical sections which damage the real-time interrupt …
> Don't require UsbBus to be Sync

- CHANGELOG.md
- src/device.rs
The UsbRev enum only has support for specification 2.0 and 2.1. Unless there's a reason not to add older revisions, 1.0 and 1.1 should also be supported.
> Support for USB 1.0 and 1.0 in UsbRev enum

- README.md
The MUSBMHDRC (musb) is a USB 2.0 Multi-Point, Dual-Role Controller designed by Mentor Graphics Corp. It is widely used in various microcontrollers and SoCs from vendors such as TI, MediaTek, Puya, and Allwinner.
I have implemented a device-driver for it in the [musb crate](https://github.com/decaday/musb), which works well on py32 microcontrollers. I have also integrated this driver into the [py32-hal](https://github.com/py32-rs/py32-hal), and written examples that can be found [here](https://github.com/py32-rs/py32-hal/tree/main/examples/usbd-f072).
In the future, I plan to test and support additional microcontrollers that utilize the MUSB IP.
> Add `musb` to hardware driver list
